### ISSUE TITLE
IOS下无法启动

### ISSUE THREAD

**Issue by qcdys** [learn-flutter-dev/flutter_qiyu#1]
IOS引用后 无法启动项目 channel 为stable

**Comment by lijy91** [comment]
有具体的错误信息吗？

**Comment by lijy91** [comment]
@

**Comment by qcdys** [comment]
> 有具体的错误信息吗？

Error output from CocoaPods:
↳
    /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/universal-darwin1
    9/rbconfig.rb:229: warning: Insecure world writable dir /Users/Juillet/Juillet in PATH,
    mode 040777
         Cloning into
         '/var/folders/yq/qdmmrlt544556vwlnykmtqrr0000gn/T/d20200715-57367-15toar5'...
         Note: checking out '******'.

         You are in 'detached HEAD' state. You can look around, make experimental
         changes and commit them, and you can discard any commits you make in this
         state without impacting any branches by performing another checkout.

         If you want to create a new branch to retain commits you create, you may
         do so (now or later) by using -b with the checkout command again. Example:

           git checkout -b <new-branch-name>

         git-lfs smudge -- 'SDK/libQYSDK.a': git-lfs: command not found
         error: external filter git-lfs smudge -- %f failed -1
         error: external filter git-lfs smudge -- %f failed
         fatal: SDK/libQYSDK.a: smudge filter lfs failed
         warning: Clone succeeded, but checkout failed.
         You can inspect what was checked out with 'git status'
         and retry the checkout with 'git checkout -f HEAD'


Error running pod install


大佬看看 搞不明白了

**Comment by qcdys** [comment]
> 有具体的错误信息吗？

可以加联系方式吗

**Comment by lijy91** [comment]
需要先安装 git-lfs，可以先安装后跑一下项目的 example

https://git-lfs.github.com/

**Comment by lijy91** [comment]
> > 有具体的错误信息吗？
> 
> 可以加联系方式吗

WeChat: lijy91

**Comment by qcdys** [comment]
> 需要先安装 git-lfs，可以先安装后跑一下项目的 example
> 
> https://git-lfs.github.com/

我试一下
