### ISSUE TITLE
IOS无法运行

### ISSUE THREAD

**Issue by you-zuo** [learn-flutter-dev/flutter_qiyu#2]
Xcode's output:
↳
    In file included from /Users/youzuo/Desktop/androidStudioProject/flutter_qiyu/ios/Classes/FlutterQiyuPlugin.m:4:
    /Users/youzuo/Desktop/androidStudioProject/flutter_qiyu/ios/Classes/UIBarButtonItem+blocks.h:22:45: warning: this block declaration is not a prototype [-Wstrict-prototypes]
    typedef void (^UIBarButtonItemActionHandler)();
                                                ^
                                                 void
    /Users/youzuo/Desktop/androidStudioProject/flutter_qiyu/ios/Classes/FlutterQiyuPlugin.m:52:44: warning: incompatible pointer to integer conversion sending 'NSInteger *' (aka 'long *') to parameter of type 'NSInteger' (aka 'long'); dereference with * [-Wint-conversion]
            result([NSNumber numberWithInteger:unreadCount]);
                                               ^~~~~~~~~~~
                                               *
    In module 'Foundation' imported from /Users/youzuo/Desktop/androidStudioProject/flutter_qiyu/example/ios/Pods/Headers/Private/QIYU_iOS_SDK/QYSDK.h:11:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.6.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSValue.h:101:44: note: passing argument to parameter 'value' here
    + (NSNumber *)numberWithInteger:(NSInteger)value API_AVAILABLE(macos(10.5), ios(2.0), watchos(2.0), tvos(9.0));
                                               ^
    /Users/youzuo/Desktop/androidStudioProject/flutter_qiyu/ios/Classes/FlutterQiyuPlugin.m:264:12: warning: incompatible integer to pointer conversion returning 'NSInteger' (aka 'long') from a function with result type 'NSInteger *' (aka 'long *'); take the address with & [-Wint-conversion]
        return count;
               ^~~~~
               &
    3 warnings generated.
    In file included from /Users/youzuo/Desktop/androidStudioProject/flutter_qiyu/ios/Classes/UIBarButtonItem+blocks.m:20:
    /Users/youzuo/Desktop/androidStudioProject/flutter_qiyu/ios/Classes/UIBarButtonItem+blocks.h:22:45: warning: this block declaration is not a prototype [-Wstrict-prototypes]
    typedef void (^UIBarButtonItemActionHandler)();
                                                ^
                                                 void
    1 warning generated.
    While building module 'flutter_qiyu' imported from /Users/youzuo/Desktop/androidStudioProject/flutter_qiyu/example/ios/Runner/GeneratedPluginRegistrant.m:8:
    In file included from <module-includes>:1:
    In file included from /Users/youzuo/Desktop/androidStudioProject/flutter_qiyu/example/ios/Pods/Headers/Public/flutter_qiyu/flutter_qiyu-umbrella.h:14:
    /Users/youzuo/Desktop/androidStudioProject/flutter_qiyu/example/ios/Pods/Headers/Public/flutter_qiyu/UIBarButtonItem+blocks.h:22:45: warning: this block declaration is not a prototype [-Wstrict-prototypes]
    typedef void (^UIBarButtonItemActionHandler)();
                                                ^
                                                 void
    1 warning generated.
    1 warning generated.
    ld: warning: ld: warning: ignoring file /Users/youzuo/Desktop/androidStudioProject/flutter_qiyu/example/ios/Pods/QIYU_iOS_SDK/SDK/libQYSDK.a, building for iOS Simulator-x86_64 but attempting to link with file built for unknown-unsupported file format ( 0x76 0x65 0x72 0x73 0x69 0x6F 0x6E 0x20 0x68 0x74 0x74 0x70 0x73 0x3A 0x2F 0x2F )ignoring file /Users/youzuo/Desktop/androidStudioProject/flutter_qiyu/example/ios/Pods/QIYU_iOS_SDK/SDK/libcrypto.a, building for iOS Simulator-x86_64 but attempting to link with file built for unknown-unsupported file format ( 0x76 0x65 0x72 0x73 0x69 0x6F 0x6E 0x20 0x68 0x74 0x74 0x70 0x73 0x3A 0x2F 0x2F )

    ld: warning: ignoring file /Users/youzuo/Desktop/androidStudioProject/flutter_qiyu/example/ios/Pods/QIYU_iOS_SDK/SDK/libevent.a, building for iOS Simulator-x86_64 but attempting to link with file built for unknown-unsupported file format ( 0x76 0x65 0x72 0x73 0x69 0x6F 0x6E 0x20 0x68 0x74 0x74 0x70 0x73 0x3A 0x2F 0x2F )
    Undefined symbols for architecture x86_64:
      "_OBJC_CLASS_$_QYUserInfo", referenced from:
          objc-class-ref in libflutter_qiyu.a(FlutterQiyuPlugin.o)
      "_OBJC_CLASS_$_QYCommodityInfo", referenced from:
          objc-class-ref in libflutter_qiyu.a(FlutterQiyuPlugin.o)
      "_OBJC_CLASS_$_QYSource", referenced from:
          objc-class-ref in libflutter_qiyu.a(FlutterQiyuPlugin.o)
      "_OBJC_CLASS_$_QYSDK", referenced from:
          objc-class-ref in libflutter_qiyu.a(FlutterQiyuPlugin.o)
    ld: symbol(s) not found for architecture x86_64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Constructing build description
    warning: Capabilities for Signing & Capabilities may not function correctly because its entitlements use a placeholder team ID. To resolve this, select a development team in the Runner editor. (in target 'Runner' from project 'Runner')

Could not build the application for the simulator.
Error launching application on iPhone 8.

**Comment by lijy91** [comment]
试下 Example 是否能正常运行呢？

**Comment by you-zuo** [comment]
不行，好像是libcrypto.a libevent.a libQYSDK.a 这三个文件拉不下拉

**Comment by lijy91** [comment]
> 不行，好像是libcrypto.a libevent.a libQYSDK.a 这三个文件拉不下拉

后面解决了吗？

**Comment by slimcheng** [comment]
```
Undefined symbols for architecture arm64:
      "_OBJC_CLASS_$_QYUserInfo", referenced from:
          objc-class-ref in flutter_qiyu(FlutterQiyuPlugin.o)
      "_OBJC_CLASS_$_QYCommodityInfo", referenced from:
          objc-class-ref in flutter_qiyu(FlutterQiyuPlugin.o)
      "_OBJC_CLASS_$_QYSource", referenced from:
          objc-class-ref in flutter_qiyu(FlutterQiyuPlugin.o)
      "_OBJC_CLASS_$_QYSDK", referenced from:
          objc-class-ref in flutter_qiyu(FlutterQiyuPlugin.o)
    ld: symbol(s) not found for architecture arm64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Constructing build description

Could not build the precompiled application for the device.

Error launching application on Slimcheng's iPhone X.
```

ios下面，也是这个问题，项目跑不起来

**Comment by slimcheng** [comment]
> 不行，好像是libcrypto.a libevent.a libQYSDK.a 这三个文件拉不下拉

兄弟，怎么解决的啊

**Comment by lijy91** [comment]
@slimcheng 参考一下 https://github.com/leanflutter/flutter_qiyu/issues/1

**Comment by slimcheng** [comment]
> @slimcheng 参考一下 #1

试了，还是下不下来，后来直接下载的[源文件](https://github.com/qiyukf/QIYU_iOS_SDK/tree/master/SDK) ，就好了

**Comment by you-zuo** [comment]
> > 不行，好像是libcrypto.a libevent.a libQYSDK.a 这三个文件拉不下拉
> 
> 兄弟，怎么解决的啊

我直接去官方下的那三个文件
